### ISSUE TITLE
Data folder is missing?

### ISSUE THREAD

**Issue by giln** [migueldeicaza/SwiftNavigationDemo#1]
Hello,

Seems Data folder is missing when I checked out the project.
Or do I need to install git Lfs?

Thanks
Gil

**Comment by migueldeicaza** [comment]
Where did you get that error?

The code currently hardcodes a path, but you can get the files from recastnav.com

**Comment by giln** [comment]
The files are missing from the Xcode project.
Ok i will download theme from recastnav )

<img width="263" alt="image" src="https://github.com/migueldeicaza/SwiftNavigationDemo/assets/10021930/30c7a5cc-4cca-4970-8450-e8f3454fe4fc">

**Comment by migueldeicaza** [comment]
Yeah those ones, you ight also need to change the path referenced in the sample

**Comment by migueldeicaza** [comment]
Added files for simplicity
